### ISSUE TITLE
issue related while installing u r application using terminal

### ISSUE THREAD

**Issue by VinMankaj** [bharathajjarapu/HackerzRec#4]
i think in the read me section while installing steps changing the directory command is (cd HackerzRec) because while clonning your application though git the files are named HackerzRec . the solution to this can be either change the read me section commad to (cd HackerzRec ) or just change the name of the file to ArcVision...

![Screenshot 2023-12-24 194747](https://github.com/bharathajjarapu/ArcVision/assets/147089487/998e096b-1b1c-4367-b27d-887ade5ba7c7)

**Comment by bharathajjarapu** [comment]
yeah i will change it thanks
